trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - WebApp/Backend/AlexaIOTInfraredRemoteAPI

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
# - script: dotnet build WebApp/Backend/AlexaIOTInfraredRemoteAPI
#   displayName: 'dotnet restore and build'

- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
    workingDirectory: 'WebApp/Backend/AlexaIOTInfraredRemoteAPI'

- task: DotNetCoreCLI@2
  displayName: publish
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'WebApp/Backend/AlexaIOTInfraredRemoteAPI/**/*.csproj'
    arguments: '--configuration Release -o $(Build.ArtifactStagingDirectory)'
    workingDirectory: 'WebApp/Backend/AlexaIOTInfraredRemoteAPI'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dotnet-app'
    publishLocation: 'Container'